id = "carbonmeda"
name = "CarbonMeda"
version = "1.0.0"
schema_version = 1
authors = ["Fyelne", "EliverLara", "cange", "ChocolateNao"]
description = "CarbonFox - Andromeda"
repository = "https://github.com/fyelne/carbonfox-andromeda"
